---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dwi67-test-wrk-deployment
  labels:
    app: dwi67-test-wrk
    username: dwi67
    env: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dwi67-test-wrk
      username: dwi67
      env: test
  template:
    metadata:
      labels:
        app: dwi67-test-wrk
        username: dwi67
        env: test
    spec:
      containers:
        - name: dwi67-test-wrk
          image: 
          imagePullPolicy: Always
          env:
          - name: redis
            value: dwi67-test-redis-service
