FROM ubuntu
FROM python:3.8.10

RUN pip install Flask==2.2.0
RUN pip install requests==2.22.0
RUN pip install redis==4.5.1
RUN pip install pyyaml==6.0
RUN pip install matplotlib==3.7.1

COPY prognosis_api.py /prognosis_api.py

CMD ["python", "prognosis_api.py"]
