FROM ubuntu
FROM python:3.8.10

RUN pip install redis==4.5.1
RUN pip install pyyaml==6.0
RUN pip install matplotlib==3.7.1
RUN pip install hotqueue==0.2.8

COPY ./src/worker.py /worker.py

CMD ["python", "worker.py"]
