---
version: "3"

services:
    redis-db:
        image: redis:7
        ports:
            - 6379:6379
        volumes:
            - ./data:/data
        user: "1000:1000"
        command: ["--save", "1", "1"]
    flask-app:
        build:
            context: ../
            dockerfile: ./docker/Dockerfile.api
        depends_on:
            - redis-db
        environment:
            - REDIS_IP=redis-db
        image: pranjaladhikari/diagnosis_app:1.0
        ports:
            - 5000:5000
        volumes:
            - ./config.yaml:/config.yaml
    flask-wrk:
        build:
            context: ../ 
            dockerfile: ./docker/Dockerfile.wrk
      # container_name: wallen-wrk
        environment:
            - REDIS_IP=redis-db
        depends_on:
            - redis-db
